#' @title Select Incident Cases by Time Since Enrollment
#'
#' @description
#' Keep only participants with incident events and classify them as occurring
#' within `n_years` or after `n_years` since enrollment. By default, the
#' function uses `outcome_surv_time` and `outcome_status` generated by
#' [build_survival_dataset()]. If the follow-up time column is not available,
#' the function can compute it from enrollment and event dates.
#'
#' @param df A data.frame or data.table.
#' @param n_years Numeric scalar. Cutoff in years for classifying incident
#'   events. Default is `5`.
#' @param time_col Column name for follow-up time in years. Default is
#'   `"outcome_surv_time"`.
#' @param status_col Column name for event status where `1` indicates an
#'   incident event. Default is `"outcome_status"`.
#' @param baseline_col Column name for enrollment date. Used only when
#'   `time_col` is not present. Default is `"p53_i0"`.
#' @param event_date_col Column name for event date. Used only when `time_col`
#'   is not present or when `status_col` is unavailable. Default is
#'   `"earliest_date"`.
#' @param group_col Name of the output grouping column. Default is
#'   `"incident_timing"`.
#' @param output Output format. `"combined"` returns one filtered data object;
#'   `"split"` returns a named list with two filtered data objects for events
#'   within and after `n_years`.
#' @param copy Logical scalar. If `TRUE` and `df` is a data.table, work on a
#'   copied object before filtering.
#' @param verbose Logical scalar. If `TRUE`, print a short selection summary.
#'
#' @return If `output = "combined"`, a filtered object with the same class as
#'   `df`, containing only participants with incident events. The output adds
#'   `group_col`. If `time_col` is missing but can be derived from dates, the
#'   function also adds `time_col`. If `output = "split"`, a named list with
#'   `within_n_years` and `after_n_years`, each preserving the same class as
#'   `df`.
#'
#' @examples
#' df <- data.frame(
#'   id = 1:5,
#'   outcome_surv_time = c(1.2, 4.9, 5.0, 8.1, 3.0),
#'   outcome_status = c(1, 1, 1, 1, 0)
#' )
#'
#' result <- select_incident_by_years(df, n_years = 5)
#' table(result$incident_timing)
#'
#' split_result <- select_incident_by_years(df, n_years = 5, output = "split")
#' names(split_result)
#'
#' @export
select_incident_by_years <- function(df,
                                     n_years = 5,
                                     time_col = "outcome_surv_time",
                                     status_col = "outcome_status",
                                     baseline_col = "p53_i0",
                                     event_date_col = "earliest_date",
                                     group_col = "incident_timing",
                                     output = c("combined", "split"),
                                     copy = TRUE,
                                     verbose = TRUE) {
  output <- match.arg(output)

  .validate_select_incident_inputs(
    df = df,
    n_years = n_years,
    time_col = time_col,
    status_col = status_col,
    baseline_col = baseline_col,
    event_date_col = event_date_col,
    group_col = group_col,
    output = output,
    copy = copy,
    verbose = verbose
  )

  dt <- df
  if (isTRUE(copy) && data.table::is.data.table(df)) {
    dt <- data.table::copy(df)
  }

  has_time_col <- time_col %in% names(dt)
  has_status_col <- status_col %in% names(dt)
  has_event_date_col <- event_date_col %in% names(dt)
  has_baseline_col <- baseline_col %in% names(dt)

  if (has_time_col) {
    incident_time <- dt[[time_col]]
    if (!is.numeric(incident_time)) {
      stop(sprintf("Time column '%s' must be numeric.", time_col))
    }
    if (any(incident_time < 0, na.rm = TRUE)) {
      stop(sprintf("Time column '%s' contains negative values.", time_col))
    }
  } else {
    if (!has_baseline_col || !has_event_date_col) {
      stop(sprintf(
        "Column '%s' is not found. Provide '%s' or both '%s' and '%s'.",
        time_col, time_col, baseline_col, event_date_col
      ))
    }

    baseline_date <- as.Date(dt[[baseline_col]])
    event_date <- as.Date(dt[[event_date_col]])
    incident_time <- as.numeric(event_date - baseline_date) / 365.25
    dt[[time_col]] <- incident_time
  }

  if (has_status_col) {
    status_vals <- dt[[status_col]]
    observed_status <- unique(status_vals[!is.na(status_vals)])
    if (!all(observed_status %in% c(0, 1))) {
      stop(sprintf(
        "Status column '%s' must use 0/1 coding for censored/event.",
        status_col
      ))
    }
    keep_idx <- !is.na(status_vals) &
      status_vals == 1 &
      !is.na(incident_time) &
      incident_time > 0
  } else {
    if (!has_event_date_col) {
      stop(sprintf(
        "Column '%s' is not found. Provide '%s' or '%s'.",
        status_col, status_col, event_date_col
      ))
    }

    keep_idx <- !is.na(dt[[event_date_col]]) &
      !is.na(incident_time) &
      incident_time > 0
  }

  if (data.table::is.data.table(dt)) {
    result <- dt[keep_idx]
  } else {
    result <- dt[keep_idx, , drop = FALSE]
  }

  cutoff_label <- .format_incident_year_label(n_years)
  within_label <- paste0("within_", cutoff_label, "_years")
  after_label <- paste0("after_", cutoff_label, "_years")

  result[[group_col]] <- ifelse(result[[time_col]] <= n_years, within_label, after_label)
  within_idx <- result[[group_col]] == within_label
  within_count <- sum(within_idx, na.rm = TRUE)
  after_count <- sum(!within_idx, na.rm = TRUE)

  if (identical(output, "split")) {
    if (data.table::is.data.table(result)) {
      result <- list(
        within_n_years = result[within_idx],
        after_n_years = result[!within_idx]
      )
    } else {
      result <- list(
        within_n_years = result[within_idx, , drop = FALSE],
        after_n_years = result[!within_idx, , drop = FALSE]
      )
    }
  }

  if (isTRUE(verbose)) {
    message("[select_incident_by_years] Complete")
    message(sprintf(
      "  Within %s years = %d, after %s years = %d, output n = %d",
      cutoff_label,
      within_count,
      cutoff_label,
      after_count,
      within_count + after_count
    ))
  }

  result
}


#' @param df The input data.
#' @param n_years Numeric cutoff in years.
#' @param time_col Name of the follow-up time column.
#' @param status_col Name of the event indicator column.
#' @param baseline_col Name of the baseline date column.
#' @param event_date_col Name of the event date column.
#' @param group_col Name of the output grouping column.
#' @param output Output mode.
#' @param copy Logical scalar.
#' @param verbose Logical scalar.
#'
#' @return NULL, invisibly.
#' @keywords internal
#' @noRd
.validate_select_incident_inputs <- function(df,
                                             n_years,
                                             time_col,
                                             status_col,
                                             baseline_col,
                                             event_date_col,
                                             group_col,
                                             output,
                                             copy,
                                             verbose) {
  if (!is.data.frame(df)) {
    stop("'df' must be a data.frame or data.table.")
  }

  if (!is.numeric(n_years) || length(n_years) != 1 || is.na(n_years) ||
      !is.finite(n_years) || n_years <= 0) {
    stop("'n_years' must be a single positive number.")
  }

  char_args <- list(
    time_col = time_col,
    status_col = status_col,
    baseline_col = baseline_col,
    event_date_col = event_date_col,
    group_col = group_col,
    output = output
  )

  for (arg_name in names(char_args)) {
    arg_value <- char_args[[arg_name]]
    if (!is.character(arg_value) || length(arg_value) != 1 || is.na(arg_value) || arg_value == "") {
      stop(sprintf("'%s' must be a single non-empty character string.", arg_name))
    }
  }

  if (!isTRUE(copy) && !identical(copy, FALSE)) {
    stop("'copy' must be TRUE or FALSE.")
  }

  if (!isTRUE(verbose) && !identical(verbose, FALSE)) {
    stop("'verbose' must be TRUE or FALSE.")
  }

  invisible(NULL)
}


#' @param n_years Numeric cutoff in years.
#'
#' @return A character scalar for display labels.
#' @keywords internal
#' @noRd
.format_incident_year_label <- function(n_years) {
  sub("\\.?0+$", "", format(n_years, scientific = FALSE, trim = TRUE))
}
